### ISSUE TITLE
上传文件图标配色

### ISSUE THREAD

**Issue by Lucas04-nhr** [hakadao/CherryStudio-Aero#1]
<img width="253" alt="Image" src="https://github.com/user-attachments/assets/377733b2-f82e-45fe-9c22-c2389cce31aa" />

如图，建议降低一点绿色的饱和度

**Comment by hakadao** [comment]
這裏主要還是弄毛玻璃效果的，如果 cherry studio 本身有問題的話建議去到 cherry studio 倉庫提，非常感謝

**Comment by Lucas04-nhr** [comment]
似乎在默认主题中没有这个 bug，似乎是在 hover 的时候原版主题会将图标自动变颜色，但是更改之后就不会了

<img width="163" alt="Image" src="https://github.com/user-attachments/assets/5e0cc2e5-bd58-4d1c-80a8-207175ca50b9" />

**Comment by Lucas04-nhr** [comment]
> 似乎在默认主题中没有这个 bug，似乎是在 hover 的时候原版主题会将图标自动变颜色，但是更改之后就不会了
> 
> <img alt="Image" width="163" src="https://private-user-images.githubusercontent.com/117806313/425906853-5e0cc2e5-bd58-4d1c-80a8-207175ca50b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDI3ODU0NjcsIm5iZiI6MTc0Mjc4NTE2NywicGF0aCI6Ii8xMTc4MDYzMTMvNDI1OTA2ODUzLTVlMGNjMmU1LWJkNTgtNGQxYy04MGE4LTIwNzE3NWNhNTBiOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMyNFQwMjU5MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOGNmMDlkOWY2NzZmMTk4Y2U1NjZhMzNlN2NlMjdkNzcwNzYwMGU4YWQwMTAzOTY0MzJiMGVlZDIzODBjMGRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.XAHCc9C7BhbUENHno9CjM0KZx4s7mf33OXouOUR1L8Y">


我尝试通过控制台定位组件的位置同时更改相应的 RGB 值，似乎可以暂时解决，但是限于本人水平不太清楚怎么编写主题的 CSS 文件。

<img width="806" alt="Image" src="https://github.com/user-attachments/assets/a29fb631-f540-45c2-b4f8-6e57ca9fd75b" />

**Comment by Lucas04-nhr** [comment]
```css
[theme-mode=light] #chat,
[theme-mode=light] [class^=SettingGroup],
[theme-mode=light] [class^=MainContainer],
[theme-mode=light] [class^=MainContent] {
  background-color: hsla(0 0% 100% / 0.4);
}

[theme-mode=light] [class=active] {
  color:antiquewhite !important;
}

[theme-mode=dark] #chat,
[theme-mode=dark] [class^=SettingGroup],
[theme-mode=dark] [class^=MainContainer],
[theme-mode=dark] [class^=MainContent] {
  background-color: hsla(0 0% 0% / 0.2);
}
```

如上，不太清楚为什么不起作用

**Comment by hakadao** [comment]
已修復，對應readme也更新
```css
/* Cherry Studio Aero Theme */
/* https://github.com/hakadao/CherryStudio-Aero */

body[theme-mode=light] {
  --fill-1: rgba(120 120 122 / 0.1);
  --fill-2: rgba(120 120 122 / 0.15);
  --fill-3: rgba(120 120 122 / 0.20);

  --color-white: var(--fill-1);
  --color-white-soft: var(--fill-2);
  --color-white-mute: var(--fill-3);
}

:root {
  --fill-1: rgba(120 120 122 / 0.15);
  --fill-2: rgba(120 120 122 / 0.20);
  --fill-3: rgba(120 120 122 / 0.25);

  --color-black: var(--fill-1);
  --color-black-soft: var(--fill-2);
  --color-black-mute: var(--fill-3);
}

@media (prefers-color-scheme: dark) {
  body[theme-mode=light] {
      background: rgba(255 255 255 / 0.3);
  }
}

@media (prefers-color-scheme: light) {
  body[theme-mode=dark] {
      background: rgba(0 0 0 / 0.2);
  }
}

[theme-mode=light] #content-container,
[theme-mode=light] .minapp-drawer .ant-drawer-body {
  background-color: rgba(120 120 122 / 0.05);
}

[theme-mode=dark] #content-container,
[theme-mode=dark] .minapp-drawer .ant-drawer-body {
  background-color: rgba(120 120 122 / 0.05);
}

.home-tabs,
[class^=ProgramSection],
[class^=IconSection],
#messages {
  background-color: transparent;
}

[class^=TopicListItem] .menu {
  background-color: transparent !important;
}

#inputbar,
.system-prompt {
  background-color: var(--fill-1);
}

[theme-mode=light] #chat,
[theme-mode=light] [class^=SettingGroup],
[theme-mode=light] [class^=MainContainer],
[theme-mode=light] [class^=MainContent] {
  background-color: hsla(0 0% 100% / 0.4);
}

[theme-mode=dark] #chat,
[theme-mode=dark] [class^=SettingGroup],
[theme-mode=dark] [class^=MainContainer],
[theme-mode=dark] [class^=MainContent] {
  background-color: hsla(0 0% 0% / 0.2);
}

[theme-mode=light] [class^=ant-modal],
[theme-mode=light] #root[style*="background: var(--color-white)"] {
  --color-white: #ffffff;
  --color-white-soft: #f2f2f2;
  --color-white-mute: #eee;

  --color-background: var(--color-white);
  --color-background-soft: var(--color-white-soft);
  --color-background-mute: var(--color-white-mute);
}

[theme-mode=dark] [class^=ant-modal] {
  --color-black: #1b1b1f;
  --color-black-soft: #262626;
  --color-black-mute: #363636;

  --color-background: var(--color-black);
  --color-background-soft: var(--color-black-soft);
  --color-background-mute: var(--color-black-mute);
}

.bubble .message-user,
[class^=ant] {
  --color-black: #1b1b1f;
  --color-black-soft: #262626;
  --color-black-mute: #363636;
  --color-white: #ffffff;
  --color-white-soft: #f2f2f2;
  --color-white-mute: #eee;

  --chat-text-user: var(--color-black);
}
```
