### ISSUE TITLE
User input messages are a bit invisible in dark mode if using the bubble message style.

### ISSUE THREAD

**Issue by LiuKay** [hakadao/CherryStudio-Aero#2]
Thank you so much for making this theme.

But I find a little issue when using dark mode with message style set to "Bubble". please check the pictures below.

Message Style: Plain
![Image](https://github.com/user-attachments/assets/909cf51b-1f0f-40fa-9e6c-7bc3bcef3fe5)

Message Style: Bubble
![Image](https://github.com/user-attachments/assets/4ca1eac3-eeac-4627-bacb-225e1604d988)

Additional details:
Cherry studio version: v1.1.7
Platform version: window11

**Comment by hakadao** [comment]
I'll try to fix it. Thanks for pointing it out

**Comment by hakadao** [comment]
已修復，對應readme也更新
```css
/* Cherry Studio Aero Theme */
/* https://github.com/hakadao/CherryStudio-Aero */

body[theme-mode=light] {
  --fill-1: rgba(120 120 122 / 0.1);
  --fill-2: rgba(120 120 122 / 0.15);
  --fill-3: rgba(120 120 122 / 0.20);

  --color-white: var(--fill-1);
  --color-white-soft: var(--fill-2);
  --color-white-mute: var(--fill-3);
}

:root {
  --fill-1: rgba(120 120 122 / 0.15);
  --fill-2: rgba(120 120 122 / 0.20);
  --fill-3: rgba(120 120 122 / 0.25);

  --color-black: var(--fill-1);
  --color-black-soft: var(--fill-2);
  --color-black-mute: var(--fill-3);
}

@media (prefers-color-scheme: dark) {
  body[theme-mode=light] {
      background: rgba(255 255 255 / 0.3);
  }
}

@media (prefers-color-scheme: light) {
  body[theme-mode=dark] {
      background: rgba(0 0 0 / 0.2);
  }
}

[theme-mode=light] #content-container,
[theme-mode=light] .minapp-drawer .ant-drawer-body {
  background-color: rgba(120 120 122 / 0.05);
}

[theme-mode=dark] #content-container,
[theme-mode=dark] .minapp-drawer .ant-drawer-body {
  background-color: rgba(120 120 122 / 0.05);
}

.home-tabs,
[class^=ProgramSection],
[class^=IconSection],
#messages {
  background-color: transparent;
}

[class^=TopicListItem] .menu {
  background-color: transparent !important;
}

#inputbar,
.system-prompt {
  background-color: var(--fill-1);
}

[theme-mode=light] #chat,
[theme-mode=light] [class^=SettingGroup],
[theme-mode=light] [class^=MainContainer],
[theme-mode=light] [class^=MainContent] {
  background-color: hsla(0 0% 100% / 0.4);
}

[theme-mode=dark] #chat,
[theme-mode=dark] [class^=SettingGroup],
[theme-mode=dark] [class^=MainContainer],
[theme-mode=dark] [class^=MainContent] {
  background-color: hsla(0 0% 0% / 0.2);
}

[theme-mode=light] [class^=ant-modal],
[theme-mode=light] #root[style*="background: var(--color-white)"] {
  --color-white: #ffffff;
  --color-white-soft: #f2f2f2;
  --color-white-mute: #eee;

  --color-background: var(--color-white);
  --color-background-soft: var(--color-white-soft);
  --color-background-mute: var(--color-white-mute);
}

[theme-mode=dark] [class^=ant-modal] {
  --color-black: #1b1b1f;
  --color-black-soft: #262626;
  --color-black-mute: #363636;

  --color-background: var(--color-black);
  --color-background-soft: var(--color-black-soft);
  --color-background-mute: var(--color-black-mute);
}

.bubble .message-user,
[class^=ant] {
  --color-black: #1b1b1f;
  --color-black-soft: #262626;
  --color-black-mute: #363636;
  --color-white: #ffffff;
  --color-white-soft: #f2f2f2;
  --color-white-mute: #eee;

  --chat-text-user: var(--color-black);
}
```
