### ISSUE TITLE
[ENHANCEMENT] 适配 1.4.2 的新版本 UI

### ISSUE THREAD

**Issue by Lucas04-nhr** [hakadao/CherryStudio-Aero#8]
在侧边栏更新后，原有的部分透明度选项会影响小程序及部分设置界面。

<img width="1080" alt="Image" src="https://github.com/user-attachments/assets/5cf5e479-57ee-4a03-ab70-0667906b5f59" />

---
> 我也在尝试进行修复，如果测试修复完成会给本仓库提 PR）

---
以下是本人的所有自定义 CSS ,但是似乎上述 bug 仅与 Aero theme 有关
```css
/* Added User Style */

/*  Font */
* {
  font-family: Product Sans, Noto Sans SC, Maple Mono NF CN Medium !important;
}

[class^="CodeBlockWrapper"],
[class^="cm"] {
  * {
    font-family: Maple Mono NF CN Medium !important;
  }
}

code,
.ant-input,
.ant-modal-confirm-content {
  font-family: Maple Mono NF CN Medium !important;
}

/*  Animation*/
@keyframes clickAnimation {
  0% {
    transform: scale(1); /* 开始时大小为 1 */
  }
  30% {
    transform: scale(0.9);
  }
  60% {
    transform: scale(1.05);
  }
  100% {
    transform: scale(1); /* 最后恢复到原始大小 */
  }
}

@keyframes page-popup-right {
  from {
    transform: translateX(-2em);
    opacity: 0%;
  }
  to {
    transform: translateX(0);
    opacity: 100%;
  }
}

@keyframes page-popup-left {
  from {
    transform: translateX(2em);
    opacity: 0%;
  }
  to {
    transform: translateX(0);
    opacity: 100%;
  }
}

/*  Color*/
:root {
  --chat-background-user-light: #5698c3;
  --chat-background-user-dark: #2b73af;
  --button-hover-light: #2983bb;
  --button-hover-dark: #1661ab;
  --input-bg-light: #e6e6e6;
  --input-bg-dark: #202020;
  --button-border-radius: 12px;
  --button-border-radius-hover: 8px;
  --button-border-radius-active: 12px;
  --background-light-new: #f3f3f3;
  --background-dark-new: #242424;
  --background-assistant-light-new: #e3e3e3;
  --animation: cubic-bezier(0.56, -0.37, 0.46, 1.58);
  --short-timer: 0.2s;
  --long-timer: 0.5s;
}

/* v1.2.8 */
[class^="Menus"] {
  [class^="Icon"]:active {
    border-radius: var(--button-border-radius-active) !important;
    transition: border-radius var(--short-timer) var(--animation);
    animation: clickAnimation var(--long-timer) var(--animation);
  }
}

/* v1.4.0 */
[theme-mode="light"] .message-content-container-user {
  background-color: var(--chat-background-user-light) !important;
}

[theme-mode="dark"] .message-content-container-user {
  background-color: var(--chat-background-user-dark) !important;
}

/* v1.4.2-ui-preview */
[class^="MainMenuItem"]:active,
.rc-virtual-list-holder-inner .ant-dropdown-trigger:active,
[class^="ListItemContainer"]:active,
[class^="AgentCardContainer"]:active {
  border-radius: var(--button-border-radius-active) !important;
  transition: border-radius var(--short-timer) var(--animation);
  animation: clickAnimation var(--long-timer) var(--animation);
}

/*  MAIN */
[class^="MessageLineContainer"] {
  background: var(--chat-background);
  border-radius: var(--button-border-radius);

  [class^="MessageItem"]:active {
    animation: clickAnimation var(--long-timer) var(--animation);
  }
}

[class^="TitleContainer"] {
  background: var(--chat-background-assistant) !important;
}

[theme-mode="dark"][id~="inputbar"] {
  background: var(input-bg-dark);
}

[class^="SettingHelpTextRow"] {
  display: inline-block;
}

[class^="Icon"],
[class^="ant"],
[class^="ActionButton"],
[class^="TopicListItem"],
[class^="ProviderListItem"],
[class^="MenuItem"],
[class^="MenuButton"],
[class^="EmojiBackground"] {
  border-radius: var(--button-border-radius) !important;
}

[class^="ant-switch"] {
  border-radius: 100px !important;
}

[theme-mode="light"] #inputbar,
[theme-mode="light"] [class^="InputContainer"] {
  background: var(--input-bg-light);
}

[theme-mode="dark"] #inputbar,
[theme-mode="dark"] [class^="InputContainer"] {
  background: var(--input-bg-dark);
}

body[theme-mode="light"] {
  background-color: var(--background-light-new);
}

body[theme-mode="dark"] {
  background-color: var(--background-dark-new) !important;
}

[theme-mode="light"] .bubble .message-user .message-action-button:hover {
  background-color: var(--button-hover-light) !important;
}

[theme-mode="dark"] .bubble .message-user .message-action-button:hover {
  background-color: var(--button-hover-dark) !important;
}

[theme-mode="light"] button.ant-btn:hover,
[theme-mode="dark"] button.ant-btn:hover {
  border-radius: var(--button-border-radius) !important;
}

[theme-mode="light"] [class^="ant-input"],
[theme-mode="light"] button.ant-btn-variant-outlined {
  background-color: var(--input-bg-light) !important;
}

[theme-mode="dark"] [class^="ant-input"],
[theme-mode="dark"] button.ant-btn-variant-outlined {
  background-color: var(--input-bg-dark) !important;
}

[class$="-tabs-content"],
[class$="-tab"],
[id^="content-container"],
[class^="MessageContainer"],
[class^="SettingContent"],
[class^="SettingContainer"],
[class^="SettingGroup"],
[class^="MenuList"],
[class^="ProviderList"],
[class^="AgentsListContainer"],
[class^="SideNav"],
[class^="MainContainer-"],
[class^="Main"],
[class~="message-assistant"] {
  animation: page-popup-right var(--short-timer) var(--animation);
}

[class~="message-user"] {
  animation: page-popup-left var(--short-timer) var(--animation);
}

[class^="Icon"]:hover,
[class^="ant"]:hover,
[class^="ActionButton"]:hover,
[class^="TopicListItem"]:hover,
[class^="ProviderListItem"]:hover,
[class^="MenuItem"]:hover,
[class^="MenuButton"]:hover,
[class^="EmojiBackground"]:hover {
  border-radius: var(--button-border-radius-hover) !important;
  transition: border-radius var(--short-timer) var(--animation);
}

[class^="IconItem"]:active,
[class^="ant-avatar"]:active,
[class^="ant-btn"]:active,
[class^="ant-segmented-item"]:active,
[class^="anticon"]:active,
[class^="ant-upload"]:active,
[class^="ant-divider"]:active,
[class^="ant-tooltip"]:active,
[class^="ant-message"]:active,
[class^="ActionButton"]:active,
[class^="TopicListItem"]:active,
[class^="ProviderListItem"]:active,
[class^="MenuItem"]:active,
[class^="MenuButton"]:active,
[class^="EmojiBackground"]:active,
[class~="ant-dropdown-menu-item"]:active,
[class~="ant-dropdown-menu-submenu-title"]:active,
[class~="ant-select-selector"]:active,
[class~="ant-select-item"]:active {
  border-radius: var(--button-border-radius-active) !important;
  transition: border-radius var(--short-timer) var(--animation);
  animation: clickAnimation var(--long-timer) var(--animation);
}

/* Cherry Studio Aero Theme */
/* https://github.com/hakadao/CherryStudio-Aero */

body[theme-mode=light] {
  --fill-1: rgba(120 120 122 / 0.1);
  --fill-2: rgba(120 120 122 / 0.15);
  --fill-3: rgba(120 120 122 / 0.20);

  --color-white: var(--fill-1);
  --color-white-soft: var(--fill-2);
  --color-white-mute: var(--fill-3);
}

:root {
  --fill-1: rgba(120 120 122 / 0.15);
  --fill-2: rgba(120 120 122 / 0.20);
  --fill-3: rgba(120 120 122 / 0.25);

  --color-black: var(--fill-1);
  --color-black-soft: var(--fill-2);
  --color-black-mute: var(--fill-3);
}

/* Fix Quick Assistant's transparent background on Windows (text hard to see) */
body[theme-mode=light][os=windows] {
  --color-background: hsla(0 0 100% / 1);
  --color-background-opacity: hsla(0 0 90% / 0.6);
}

/* Fix Quick Assistant's transparent background on Windows (text hard to see) */
body[theme-mode=dark][os=windows] {
  --color-background: hsla(0 0 8% / 1);
  --color-background-opacity: hsla(0 0 8% / 0.6);
}

@media (prefers-color-scheme: dark) {
  body[theme-mode=light] {
      background: rgba(255 255 255 / 0.3);
  }
}

@media (prefers-color-scheme: light) {
  body[theme-mode=dark] {
      background: rgba(0 0 0 / 0.2);
  }
}

[theme-mode=light] #content-container,
[theme-mode=light] .minapp-drawer .ant-drawer-body {
  background-color: rgba(120 120 122 / 0.05);
}

[theme-mode=dark] #content-container,
[theme-mode=dark] .minapp-drawer .ant-drawer-body {
  background-color: rgba(120 120 122 / 0.05);
}

.home-tabs,
[class^=ProgramSection],
[class^=IconSection],
#messages, 
[class^=SettingContainer] {
  background-color: transparent;
}

[class^=TopicListItem] .menu {
  background-color: transparent !important;
}

#inputbar,
.system-prompt,
[class^=CardContent],
[class^=ServerCard] {
  background-color: var(--fill-1);
}

[theme-mode=light] #chat,
[theme-mode=light] [class^=SettingGroup],
[theme-mode=light] [class^=MainContainer],
[theme-mode=light] [class^=MainContent] {
  background-color: hsla(0 0% 100% / 0.4);
}

/* On the right side of "Model Provider" in Settings */
[theme-mode=light] [class^=ProviderListContainer] + [class^=SettingContainer] {
  background: hsla(0 0% 100% / 0.4) !important;
}

[theme-mode=dark] #chat,
[theme-mode=dark] [class^=SettingGroup],
[theme-mode=dark] [class^=MainContainer],
[theme-mode=dark] [class^=MainContent] {
  background-color: hsla(0 0% 0% / 0.2);
}

/* On the right side of "Model Provider" in Settings */
[theme-mode=dark] [class^=ProviderListContainer] + [class^=SettingContainer] {
  background: hsla(0 0% 0% / 0.2) !important;
}

[theme-mode=light] [class^=ant-modal],
[theme-mode=light] #root[style*="background: var(--color-white)"] {
  --color-white: #ffffff;
  --color-white-soft: #f2f2f2;
  --color-white-mute: #eee;

  --color-background: var(--color-white);
  --color-background-soft: var(--color-white-soft);
  --color-background-mute: var(--color-white-mute);
}

[theme-mode=dark] [class^=ant-modal] {
  --color-black: #1b1b1f;
  --color-black-soft: #262626;
  --color-black-mute: #363636;

  --color-background: var(--color-black);
  --color-background-soft: var(--color-black-soft);
  --color-background-mute: var(--color-black-mute);
}

.bubble .message-user,
[class^=ant] {
  --color-black: #1b1b1f;
  --color-black-soft: #262626;
  --color-black-mute: #363636;
  --color-white: #ffffff;
  --color-white-soft: #f2f2f2;
  --color-white-mute: #eee;

  --chat-text-user: var(--color-black);
}
```
